### ISSUE TITLE
#include不支持../引用父级目录

### ISSUE THREAD

**Issue by colorpeach** [pavelpower/node-ftl#3]
没法include父级目录里的模板

```
Error reading included file ../public.ftl The problematic instruction: ---------- ==> 
include "../public.ftl" [on line 1,
 column 1 in template.ftl] in include "./template.ftl" [on line 1, column 1 in index.ftl] 
---------- Java backtrace for programmers: ---------- 
freemarker.template.TemplateException: Error reading included file ../public.ftl at freemarker.core.Include.accept(Include.java:167) at freemarker.core.Environment.visit(Environment.java:221) at 
freemarker.core.MixedContent.accept(MixedContent.java:92) at 
freemarker.core.Environment.visit(Environment.java:221) at 
freemarker.core.Environment.include(Environment.java:1508) at 
freemarker.core.Include.accept(Include.java:169) at 
freemarker.core.Environment.visit(Environment.java:221) at 
freemarker.core.MixedContent.accept(MixedContent.java:92) at 
freemarker.core.Environment.visit(Environment.java:221) at 
freemarker.core.Environment.process(Environment.java:199) at 
freemarker.template.Template.process(Template.java:259) at 
cn.ijser.util.FreeMarkerUtil.processTemplate(FreeMarkerUtil.java:47) at 
cn.ijser.app.FMtoll.main(FMtoll.java:36) Caused by: java.io.FileNotFoundException: Template ../public.ftl not found. at freemarker.template.Configuration.getTemplate(Configuration.java:580) at 
freemarker.core.Environment.getTemplateForInclusion(Environment.java:1490) at 
freemarker.core.Include.accept(Include.java:157) ... 12 more

```

**Comment by pavelpower** [comment]
Hello! Thk!

Look on this example:

File structure
`./views/public/public.ftl`
`./views/pages/index.ftl`

parser:

``` javascript
              ftl.processTemplate({
                    data: data,
                    settings: {
                        encoding: 'utf-8',
                        // !!!!!!! it is the base folder for freemarker !!!!!!!
                        viewFolder: path.join(process.cwd(), '/views')
                    },
                    // !!!!! the relative path from the "viewFolder" folder !!!!!
                    filename: './pages/index.ftl'
                }).on('error', function(err) {
                    if (err)
                        throw err;
                }).on('end', function(err, html) {
                    console.log(html);
                })
```

ok, and `./views/pages/index.ftl`:

``` html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta name="Author" content="CTI" />
    <meta name="viewport" content="width=1280" />

    <title id="page-title">Node FTL</title>
    <#include "../public/public.ftl" >
</head>

<body>
 <h1>Test ftl builder</h1>

 <#if (RequestParameters.optjs) == "true" >
      <h2>Param optjs is enabled</h2>
 </#if>
 <#if (RequestParameters.ie) == "1" >
      <h2>Param ie is enabled</h2>
 </#if>
</body>
</html>
```

and `views/public/public.ftl`:

``` html
<script>
    window.alert('hello world');
</script>
```

result: 

``` html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta name="Author" content="CTI" />
    <meta name="viewport" content="width=1280" />

    <title id="page-title">Node FTL</title>
    <script>
    window.alert('hello world');
</script></head>

<body>
 <h1>Test ftl builder</h1>

      <h2>Param optjs is enabled</h2>
</body>

</html>

```
